[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true }
api = { workspace = true }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", version = "0.0.1", default-features = false, features = ["router"] }
tokio = { version = "1.0", features = ["time"], optional = true }

[features]
server = ["api/server"]
